void nav_button(int x, int y, int width, int height, char text[]);
void nav_button_clicked(int x, int y, int width, int height, char text[]);
void button(int x, int y, int width, int height, char text[], int x_offset);
void button_clicked(int x, int y, int width, int height, char text[], int x_offset);
int word_button(int x, int y, int width, int height);
int word_button_clicked(int x, int y, int width, int height);
void background_brick(int x, int y);
void foreground_brick(int x, int y);
void background(int x, int y);
void foreground(int x, int y);
void torch(int x, int y);
void display_text(int x, int y, char input[10]);
void input_box(int x, int y, char guess[10], char set[10],int m);
void puzzle_letter(int x, int y, char set[10]);
void guess_board(int y, int xsize, int end, int counter, char guess_list[35][10], char correct_guess[35][10]);
void guess_board_letter(int xsize, int end, int counter, char guess_list[35][10], char correct_guess[35][10]);
